spring:
  datasource:
    url: jdbc:postgresql://ep-plain-star-47974789.us-east-2.aws.neon.tech:5432/notesdb?sslmode=require
    username: fl0user
    password: Ju9ea4sIrMSR
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        type: trace
server:
  port: 8080