spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appnotes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
server:
  port: 3000