name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Build project
        run: mvn clean install -DskipTests
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
          username: fdreer
          password: 8B72g3k5@
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fdreer/app-notes/springboot:latest

  deploy:
    needs: build
    runs-on: [app-notes-runner]
    steps:
      - name: Pull image from docker hub
        run: docker pull in app-notes/springboot
      - name: Delete old container
        run: docker rm -f appnotes-springboot-container
      - name: RUN docker container
        run: docker run -d -p 8080:8080 --name appnotes-springboot-container app-notes/springboot