name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t app-notes/springboot .
      - name: Publish image to docker hub
        run: docker push app-notes/springboot:latest

  deploy:
    needs: build
    runs-on: [app-notes-runner]
    steps:
      - name: Pull image from docker hub
        run: docker pull in app-notes/springboot:latest
      - name: Delete old container
        run: docker rm -f appnotes-springboot-container
      - name: RUN docker container
        run: docker run -d -p 8080:8080 --name appnotes-springboot-container app-notes/springboot